# Copyright 2026 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

default:
  before_script:
    - source ./iis-env.sh
    - export BENDER_NO_PROGRESS=true
    - >-
      make
      HYPER_NONFREE_REMOTE="https://gitlab-ci-token:${CI_JOB_TOKEN}@iis-git.ee.ethz.ch/pulp-restricted/hyperbus-nonfree.git"
      hyper-nonfree-init

stages:
  - validate
  - test

restricted-package:
  stage: validate
  timeout: 10 minutes
  script:
    - bender -d nonfree checkout
    - make check-targets
    - >-
      bender -d nonfree script vsim
      --vlog-arg="-suppress vlog-2583 -suppress vlog-13314"
      -t rtl -t asic -t gf22 -t gf22_backend
      > nonfree_gf22_compile.tcl
    - >-
      ${VSIM} -c -l nonfree_gf22_compile.log
      -do 'if {[catch {source nonfree_gf22_compile.tcl} result]}
      {puts stderr $result; quit -code 1}; quit -code 0'
    - make gf22-validate
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - nonfree_gf22_compile.log

rtl-regression:
  stage: test
  timeout: 60 minutes
  script:
    - make models/s27ks0641
    - make run
    - make run-pad-delay-matrix
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - sim_run*.log
      - test/pad_delay_matrix/*.log
      - test/pad_delay_matrix/summary.csv
      - transcript
