// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package hyperbus_cfg_regblock_pkg;

    localparam HYPERBUS_CFG_REGBLOCK_DATA_WIDTH = 32;
    localparam HYPERBUS_CFG_REGBLOCK_MIN_ADDR_WIDTH = 7;
    localparam HYPERBUS_CFG_REGBLOCK_SIZE = 'h78;

    typedef struct {
        logic [3:0] value;
    } hyperbus_cfg_regs__t_latency_access__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_latency_access__value__out_t value;
    } hyperbus_cfg_regs__t_latency_access__out_t;

    typedef struct {
        logic value;
    } hyperbus_cfg_regs__en_latency_additional__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__en_latency_additional__value__out_t value;
    } hyperbus_cfg_regs__en_latency_additional__out_t;

    typedef struct {
        logic [15:0] value;
    } hyperbus_cfg_regs__t_burst_max__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_burst_max__value__out_t value;
    } hyperbus_cfg_regs__t_burst_max__out_t;

    typedef struct {
        logic [3:0] value;
    } hyperbus_cfg_regs__t_read_write_recovery__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_read_write_recovery__value__out_t value;
    } hyperbus_cfg_regs__t_read_write_recovery__out_t;

    typedef struct {
        logic [4:0] value;
    } hyperbus_cfg_regs__t_rx_clk_delay__fine__out_t;

    typedef struct {
        logic [2:0] value;
    } hyperbus_cfg_regs__t_rx_clk_delay__coarse__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_rx_clk_delay__fine__out_t fine;
        hyperbus_cfg_regs__t_rx_clk_delay__coarse__out_t coarse;
    } hyperbus_cfg_regs__t_rx_clk_delay__out_t;

    typedef struct {
        logic [4:0] value;
    } hyperbus_cfg_regs__t_tx_clk_delay__fine__out_t;

    typedef struct {
        logic [2:0] value;
    } hyperbus_cfg_regs__t_tx_clk_delay__coarse__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_tx_clk_delay__fine__out_t fine;
        hyperbus_cfg_regs__t_tx_clk_delay__coarse__out_t coarse;
    } hyperbus_cfg_regs__t_tx_clk_delay__out_t;

    typedef struct {
        logic [4:0] value;
    } hyperbus_cfg_regs__address_mask_msb__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__address_mask_msb__value__out_t value;
    } hyperbus_cfg_regs__address_mask_msb__out_t;

    typedef struct {
        logic value;
    } hyperbus_cfg_regs__address_space__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__address_space__value__out_t value;
    } hyperbus_cfg_regs__address_space__out_t;

    typedef struct {
        logic value;
    } hyperbus_cfg_regs__phys_in_use__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__phys_in_use__value__out_t value;
    } hyperbus_cfg_regs__phys_in_use__out_t;

    typedef struct {
        logic value;
    } hyperbus_cfg_regs__which_phy__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__which_phy__value__out_t value;
    } hyperbus_cfg_regs__which_phy__out_t;

    typedef struct {
        logic [3:0] value;
    } hyperbus_cfg_regs__t_csh_cycles__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_csh_cycles__value__out_t value;
    } hyperbus_cfg_regs__t_csh_cycles__out_t;

    typedef struct {
        logic [3:0] value;
    } hyperbus_cfg_regs__csn_to_ck_cycles__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__csn_to_ck_cycles__value__out_t value;
    } hyperbus_cfg_regs__csn_to_ck_cycles__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip0_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip0_base__value__out_t value;
    } hyperbus_cfg_regs__chip0_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip0_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip0_bound__value__out_t value;
    } hyperbus_cfg_regs__chip0_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip1_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip1_base__value__out_t value;
    } hyperbus_cfg_regs__chip1_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip1_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip1_bound__value__out_t value;
    } hyperbus_cfg_regs__chip1_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip2_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip2_base__value__out_t value;
    } hyperbus_cfg_regs__chip2_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip2_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip2_bound__value__out_t value;
    } hyperbus_cfg_regs__chip2_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip3_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip3_base__value__out_t value;
    } hyperbus_cfg_regs__chip3_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip3_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip3_bound__value__out_t value;
    } hyperbus_cfg_regs__chip3_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip4_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip4_base__value__out_t value;
    } hyperbus_cfg_regs__chip4_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip4_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip4_bound__value__out_t value;
    } hyperbus_cfg_regs__chip4_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip5_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip5_base__value__out_t value;
    } hyperbus_cfg_regs__chip5_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip5_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip5_bound__value__out_t value;
    } hyperbus_cfg_regs__chip5_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip6_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip6_base__value__out_t value;
    } hyperbus_cfg_regs__chip6_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip6_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip6_bound__value__out_t value;
    } hyperbus_cfg_regs__chip6_bound__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip7_base__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip7_base__value__out_t value;
    } hyperbus_cfg_regs__chip7_base__out_t;

    typedef struct {
        logic [9:0] value;
    } hyperbus_cfg_regs__chip7_bound__value__out_t;

    typedef struct {
        hyperbus_cfg_regs__chip7_bound__value__out_t value;
    } hyperbus_cfg_regs__chip7_bound__out_t;

    typedef struct {
        hyperbus_cfg_regs__t_latency_access__out_t t_latency_access;
        hyperbus_cfg_regs__en_latency_additional__out_t en_latency_additional;
        hyperbus_cfg_regs__t_burst_max__out_t t_burst_max;
        hyperbus_cfg_regs__t_read_write_recovery__out_t t_read_write_recovery;
        hyperbus_cfg_regs__t_rx_clk_delay__out_t t_rx_clk_delay;
        hyperbus_cfg_regs__t_tx_clk_delay__out_t t_tx_clk_delay;
        hyperbus_cfg_regs__address_mask_msb__out_t address_mask_msb;
        hyperbus_cfg_regs__address_space__out_t address_space;
        hyperbus_cfg_regs__phys_in_use__out_t phys_in_use;
        hyperbus_cfg_regs__which_phy__out_t which_phy;
        hyperbus_cfg_regs__t_csh_cycles__out_t t_csh_cycles;
        hyperbus_cfg_regs__csn_to_ck_cycles__out_t csn_to_ck_cycles;
        hyperbus_cfg_regs__chip0_base__out_t chip0_base;
        hyperbus_cfg_regs__chip0_bound__out_t chip0_bound;
        hyperbus_cfg_regs__chip1_base__out_t chip1_base;
        hyperbus_cfg_regs__chip1_bound__out_t chip1_bound;
        hyperbus_cfg_regs__chip2_base__out_t chip2_base;
        hyperbus_cfg_regs__chip2_bound__out_t chip2_bound;
        hyperbus_cfg_regs__chip3_base__out_t chip3_base;
        hyperbus_cfg_regs__chip3_bound__out_t chip3_bound;
        hyperbus_cfg_regs__chip4_base__out_t chip4_base;
        hyperbus_cfg_regs__chip4_bound__out_t chip4_bound;
        hyperbus_cfg_regs__chip5_base__out_t chip5_base;
        hyperbus_cfg_regs__chip5_bound__out_t chip5_bound;
        hyperbus_cfg_regs__chip6_base__out_t chip6_base;
        hyperbus_cfg_regs__chip6_bound__out_t chip6_bound;
        hyperbus_cfg_regs__chip7_base__out_t chip7_base;
        hyperbus_cfg_regs__chip7_bound__out_t chip7_bound;
    } hyperbus_cfg_regs__out_t;
endpackage
