// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module hyperbus_cfg_regblock (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [6:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        output hyperbus_cfg_regblock_pkg::hyperbus_cfg_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [6:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[6:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic t_latency_access;
        logic en_latency_additional;
        logic t_burst_max;
        logic t_read_write_recovery;
        logic t_rx_clk_delay;
        logic t_tx_clk_delay;
        logic address_mask_msb;
        logic address_space;
        logic phys_in_use;
        logic which_phy;
        logic t_csh_cycles;
        logic csn_to_ck_cycles;
        logic chip0_base;
        logic chip0_bound;
        logic chip1_base;
        logic chip1_bound;
        logic chip2_base;
        logic chip2_bound;
        logic chip3_base;
        logic chip3_bound;
        logic chip4_base;
        logic chip4_bound;
        logic chip5_base;
        logic chip5_bound;
        logic chip6_base;
        logic chip6_bound;
        logic chip7_base;
        logic chip7_bound;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [6:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.t_latency_access = cpuif_req_masked & (cpuif_addr == 7'h0);
        decoded_reg_strb.en_latency_additional = cpuif_req_masked & (cpuif_addr == 7'h4);
        decoded_reg_strb.t_burst_max = cpuif_req_masked & (cpuif_addr == 7'h8);
        decoded_reg_strb.t_read_write_recovery = cpuif_req_masked & (cpuif_addr == 7'hc);
        decoded_reg_strb.t_rx_clk_delay = cpuif_req_masked & (cpuif_addr == 7'h10);
        decoded_reg_strb.t_tx_clk_delay = cpuif_req_masked & (cpuif_addr == 7'h14);
        decoded_reg_strb.address_mask_msb = cpuif_req_masked & (cpuif_addr == 7'h18);
        decoded_reg_strb.address_space = cpuif_req_masked & (cpuif_addr == 7'h1c);
        decoded_reg_strb.phys_in_use = cpuif_req_masked & (cpuif_addr == 7'h20);
        decoded_reg_strb.which_phy = cpuif_req_masked & (cpuif_addr == 7'h24);
        decoded_reg_strb.t_csh_cycles = cpuif_req_masked & (cpuif_addr == 7'h28);
        decoded_reg_strb.csn_to_ck_cycles = cpuif_req_masked & (cpuif_addr == 7'h2c);
        decoded_reg_strb.chip0_base = cpuif_req_masked & (cpuif_addr == 7'h30);
        decoded_reg_strb.chip0_bound = cpuif_req_masked & (cpuif_addr == 7'h34);
        decoded_reg_strb.chip1_base = cpuif_req_masked & (cpuif_addr == 7'h38);
        decoded_reg_strb.chip1_bound = cpuif_req_masked & (cpuif_addr == 7'h3c);
        decoded_reg_strb.chip2_base = cpuif_req_masked & (cpuif_addr == 7'h40);
        decoded_reg_strb.chip2_bound = cpuif_req_masked & (cpuif_addr == 7'h44);
        decoded_reg_strb.chip3_base = cpuif_req_masked & (cpuif_addr == 7'h48);
        decoded_reg_strb.chip3_bound = cpuif_req_masked & (cpuif_addr == 7'h4c);
        decoded_reg_strb.chip4_base = cpuif_req_masked & (cpuif_addr == 7'h58);
        decoded_reg_strb.chip4_bound = cpuif_req_masked & (cpuif_addr == 7'h5c);
        decoded_reg_strb.chip5_base = cpuif_req_masked & (cpuif_addr == 7'h60);
        decoded_reg_strb.chip5_bound = cpuif_req_masked & (cpuif_addr == 7'h64);
        decoded_reg_strb.chip6_base = cpuif_req_masked & (cpuif_addr == 7'h68);
        decoded_reg_strb.chip6_bound = cpuif_req_masked & (cpuif_addr == 7'h6c);
        decoded_reg_strb.chip7_base = cpuif_req_masked & (cpuif_addr == 7'h70);
        decoded_reg_strb.chip7_bound = cpuif_req_masked & (cpuif_addr == 7'h74);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } value;
        } t_latency_access;
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } en_latency_additional;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } value;
        } t_burst_max;
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } value;
        } t_read_write_recovery;
        struct {
            struct {
                logic [4:0] next;
                logic load_next;
            } fine;
            struct {
                logic [2:0] next;
                logic load_next;
            } coarse;
        } t_rx_clk_delay;
        struct {
            struct {
                logic [4:0] next;
                logic load_next;
            } fine;
            struct {
                logic [2:0] next;
                logic load_next;
            } coarse;
        } t_tx_clk_delay;
        struct {
            struct {
                logic [4:0] next;
                logic load_next;
            } value;
        } address_mask_msb;
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } address_space;
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } phys_in_use;
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } which_phy;
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } value;
        } t_csh_cycles;
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } value;
        } csn_to_ck_cycles;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip0_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip0_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip1_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip1_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip2_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip2_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip3_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip3_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip4_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip4_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip5_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip5_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip6_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip6_bound;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip7_base;
        struct {
            struct {
                logic [9:0] next;
                logic load_next;
            } value;
        } chip7_bound;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [3:0] value;
            } value;
        } t_latency_access;
        struct {
            struct {
                logic value;
            } value;
        } en_latency_additional;
        struct {
            struct {
                logic [15:0] value;
            } value;
        } t_burst_max;
        struct {
            struct {
                logic [3:0] value;
            } value;
        } t_read_write_recovery;
        struct {
            struct {
                logic [4:0] value;
            } fine;
            struct {
                logic [2:0] value;
            } coarse;
        } t_rx_clk_delay;
        struct {
            struct {
                logic [4:0] value;
            } fine;
            struct {
                logic [2:0] value;
            } coarse;
        } t_tx_clk_delay;
        struct {
            struct {
                logic [4:0] value;
            } value;
        } address_mask_msb;
        struct {
            struct {
                logic value;
            } value;
        } address_space;
        struct {
            struct {
                logic value;
            } value;
        } phys_in_use;
        struct {
            struct {
                logic value;
            } value;
        } which_phy;
        struct {
            struct {
                logic [3:0] value;
            } value;
        } t_csh_cycles;
        struct {
            struct {
                logic [3:0] value;
            } value;
        } csn_to_ck_cycles;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip0_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip0_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip1_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip1_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip2_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip2_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip3_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip3_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip4_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip4_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip5_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip5_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip6_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip6_bound;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip7_base;
        struct {
            struct {
                logic [9:0] value;
            } value;
        } chip7_bound;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: hyperbus_cfg_regs.t_latency_access.value
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_latency_access.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_latency_access && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_latency_access.value.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.t_latency_access.value.next = next_c;
        field_combo.t_latency_access.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_latency_access.value.value <= 4'h6;
        end else begin
            if(field_combo.t_latency_access.value.load_next) begin
                field_storage.t_latency_access.value.value <= field_combo.t_latency_access.value.next;
            end
        end
    end
    assign hwif_out.t_latency_access.value.value = field_storage.t_latency_access.value.value;
    // Field: hyperbus_cfg_regs.en_latency_additional.value
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.en_latency_additional.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.en_latency_additional && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.en_latency_additional.value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.en_latency_additional.value.next = next_c;
        field_combo.en_latency_additional.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.en_latency_additional.value.value <= 1'h0;
        end else begin
            if(field_combo.en_latency_additional.value.load_next) begin
                field_storage.en_latency_additional.value.value <= field_combo.en_latency_additional.value.next;
            end
        end
    end
    assign hwif_out.en_latency_additional.value.value = field_storage.en_latency_additional.value.value;
    // Field: hyperbus_cfg_regs.t_burst_max.value
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_burst_max.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_burst_max && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_burst_max.value.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.t_burst_max.value.next = next_c;
        field_combo.t_burst_max.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_burst_max.value.value <= 16'h15e;
        end else begin
            if(field_combo.t_burst_max.value.load_next) begin
                field_storage.t_burst_max.value.value <= field_combo.t_burst_max.value.next;
            end
        end
    end
    assign hwif_out.t_burst_max.value.value = field_storage.t_burst_max.value.value;
    // Field: hyperbus_cfg_regs.t_read_write_recovery.value
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_read_write_recovery.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_read_write_recovery && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_read_write_recovery.value.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.t_read_write_recovery.value.next = next_c;
        field_combo.t_read_write_recovery.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_read_write_recovery.value.value <= 4'h6;
        end else begin
            if(field_combo.t_read_write_recovery.value.load_next) begin
                field_storage.t_read_write_recovery.value.value <= field_combo.t_read_write_recovery.value.next;
            end
        end
    end
    assign hwif_out.t_read_write_recovery.value.value = field_storage.t_read_write_recovery.value.value;
    // Field: hyperbus_cfg_regs.t_rx_clk_delay.fine
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_rx_clk_delay.fine.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_rx_clk_delay && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_rx_clk_delay.fine.value & ~decoded_wr_biten[4:0]) | (decoded_wr_data[4:0] & decoded_wr_biten[4:0]);
            load_next_c = '1;
        end
        field_combo.t_rx_clk_delay.fine.next = next_c;
        field_combo.t_rx_clk_delay.fine.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_rx_clk_delay.fine.value <= 5'h10;
        end else begin
            if(field_combo.t_rx_clk_delay.fine.load_next) begin
                field_storage.t_rx_clk_delay.fine.value <= field_combo.t_rx_clk_delay.fine.next;
            end
        end
    end
    assign hwif_out.t_rx_clk_delay.fine.value = field_storage.t_rx_clk_delay.fine.value;
    // Field: hyperbus_cfg_regs.t_rx_clk_delay.coarse
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_rx_clk_delay.coarse.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_rx_clk_delay && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_rx_clk_delay.coarse.value & ~decoded_wr_biten[7:5]) | (decoded_wr_data[7:5] & decoded_wr_biten[7:5]);
            load_next_c = '1;
        end
        field_combo.t_rx_clk_delay.coarse.next = next_c;
        field_combo.t_rx_clk_delay.coarse.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_rx_clk_delay.coarse.value <= 3'h0;
        end else begin
            if(field_combo.t_rx_clk_delay.coarse.load_next) begin
                field_storage.t_rx_clk_delay.coarse.value <= field_combo.t_rx_clk_delay.coarse.next;
            end
        end
    end
    assign hwif_out.t_rx_clk_delay.coarse.value = field_storage.t_rx_clk_delay.coarse.value;
    // Field: hyperbus_cfg_regs.t_tx_clk_delay.fine
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_tx_clk_delay.fine.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_tx_clk_delay && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_tx_clk_delay.fine.value & ~decoded_wr_biten[4:0]) | (decoded_wr_data[4:0] & decoded_wr_biten[4:0]);
            load_next_c = '1;
        end
        field_combo.t_tx_clk_delay.fine.next = next_c;
        field_combo.t_tx_clk_delay.fine.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_tx_clk_delay.fine.value <= 5'h10;
        end else begin
            if(field_combo.t_tx_clk_delay.fine.load_next) begin
                field_storage.t_tx_clk_delay.fine.value <= field_combo.t_tx_clk_delay.fine.next;
            end
        end
    end
    assign hwif_out.t_tx_clk_delay.fine.value = field_storage.t_tx_clk_delay.fine.value;
    // Field: hyperbus_cfg_regs.t_tx_clk_delay.coarse
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_tx_clk_delay.coarse.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_tx_clk_delay && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_tx_clk_delay.coarse.value & ~decoded_wr_biten[7:5]) | (decoded_wr_data[7:5] & decoded_wr_biten[7:5]);
            load_next_c = '1;
        end
        field_combo.t_tx_clk_delay.coarse.next = next_c;
        field_combo.t_tx_clk_delay.coarse.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_tx_clk_delay.coarse.value <= 3'h0;
        end else begin
            if(field_combo.t_tx_clk_delay.coarse.load_next) begin
                field_storage.t_tx_clk_delay.coarse.value <= field_combo.t_tx_clk_delay.coarse.next;
            end
        end
    end
    assign hwif_out.t_tx_clk_delay.coarse.value = field_storage.t_tx_clk_delay.coarse.value;
    // Field: hyperbus_cfg_regs.address_mask_msb.value
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.address_mask_msb.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.address_mask_msb && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.address_mask_msb.value.value & ~decoded_wr_biten[4:0]) | (decoded_wr_data[4:0] & decoded_wr_biten[4:0]);
            load_next_c = '1;
        end
        field_combo.address_mask_msb.value.next = next_c;
        field_combo.address_mask_msb.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.address_mask_msb.value.value <= 5'h19;
        end else begin
            if(field_combo.address_mask_msb.value.load_next) begin
                field_storage.address_mask_msb.value.value <= field_combo.address_mask_msb.value.next;
            end
        end
    end
    assign hwif_out.address_mask_msb.value.value = field_storage.address_mask_msb.value.value;
    // Field: hyperbus_cfg_regs.address_space.value
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.address_space.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.address_space && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.address_space.value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.address_space.value.next = next_c;
        field_combo.address_space.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.address_space.value.value <= 1'h0;
        end else begin
            if(field_combo.address_space.value.load_next) begin
                field_storage.address_space.value.value <= field_combo.address_space.value.next;
            end
        end
    end
    assign hwif_out.address_space.value.value = field_storage.address_space.value.value;
    // Field: hyperbus_cfg_regs.phys_in_use.value
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.phys_in_use.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.phys_in_use && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.phys_in_use.value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.phys_in_use.value.next = next_c;
        field_combo.phys_in_use.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.phys_in_use.value.value <= 1'h1;
        end else begin
            if(field_combo.phys_in_use.value.load_next) begin
                field_storage.phys_in_use.value.value <= field_combo.phys_in_use.value.next;
            end
        end
    end
    assign hwif_out.phys_in_use.value.value = field_storage.phys_in_use.value.value;
    // Field: hyperbus_cfg_regs.which_phy.value
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.which_phy.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.which_phy && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.which_phy.value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.which_phy.value.next = next_c;
        field_combo.which_phy.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.which_phy.value.value <= 1'h1;
        end else begin
            if(field_combo.which_phy.value.load_next) begin
                field_storage.which_phy.value.value <= field_combo.which_phy.value.next;
            end
        end
    end
    assign hwif_out.which_phy.value.value = field_storage.which_phy.value.value;
    // Field: hyperbus_cfg_regs.t_csh_cycles.value
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.t_csh_cycles.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.t_csh_cycles && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.t_csh_cycles.value.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.t_csh_cycles.value.next = next_c;
        field_combo.t_csh_cycles.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.t_csh_cycles.value.value <= 4'h1;
        end else begin
            if(field_combo.t_csh_cycles.value.load_next) begin
                field_storage.t_csh_cycles.value.value <= field_combo.t_csh_cycles.value.next;
            end
        end
    end
    assign hwif_out.t_csh_cycles.value.value = field_storage.t_csh_cycles.value.value;
    // Field: hyperbus_cfg_regs.csn_to_ck_cycles.value
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.csn_to_ck_cycles.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.csn_to_ck_cycles && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.csn_to_ck_cycles.value.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.csn_to_ck_cycles.value.next = next_c;
        field_combo.csn_to_ck_cycles.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.csn_to_ck_cycles.value.value <= 4'h0;
        end else begin
            if(field_combo.csn_to_ck_cycles.value.load_next) begin
                field_storage.csn_to_ck_cycles.value.value <= field_combo.csn_to_ck_cycles.value.next;
            end
        end
    end
    assign hwif_out.csn_to_ck_cycles.value.value = field_storage.csn_to_ck_cycles.value.value;
    // Field: hyperbus_cfg_regs.chip0_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip0_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip0_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip0_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip0_base.value.next = next_c;
        field_combo.chip0_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip0_base.value.value <= 10'h0;
        end else begin
            if(field_combo.chip0_base.value.load_next) begin
                field_storage.chip0_base.value.value <= field_combo.chip0_base.value.next;
            end
        end
    end
    assign hwif_out.chip0_base.value.value = field_storage.chip0_base.value.value;
    // Field: hyperbus_cfg_regs.chip0_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip0_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip0_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip0_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip0_bound.value.next = next_c;
        field_combo.chip0_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip0_bound.value.value <= 10'h1;
        end else begin
            if(field_combo.chip0_bound.value.load_next) begin
                field_storage.chip0_bound.value.value <= field_combo.chip0_bound.value.next;
            end
        end
    end
    assign hwif_out.chip0_bound.value.value = field_storage.chip0_bound.value.value;
    // Field: hyperbus_cfg_regs.chip1_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip1_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip1_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip1_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip1_base.value.next = next_c;
        field_combo.chip1_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip1_base.value.value <= 10'h1;
        end else begin
            if(field_combo.chip1_base.value.load_next) begin
                field_storage.chip1_base.value.value <= field_combo.chip1_base.value.next;
            end
        end
    end
    assign hwif_out.chip1_base.value.value = field_storage.chip1_base.value.value;
    // Field: hyperbus_cfg_regs.chip1_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip1_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip1_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip1_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip1_bound.value.next = next_c;
        field_combo.chip1_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip1_bound.value.value <= 10'h2;
        end else begin
            if(field_combo.chip1_bound.value.load_next) begin
                field_storage.chip1_bound.value.value <= field_combo.chip1_bound.value.next;
            end
        end
    end
    assign hwif_out.chip1_bound.value.value = field_storage.chip1_bound.value.value;
    // Field: hyperbus_cfg_regs.chip2_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip2_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip2_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip2_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip2_base.value.next = next_c;
        field_combo.chip2_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip2_base.value.value <= 10'h2;
        end else begin
            if(field_combo.chip2_base.value.load_next) begin
                field_storage.chip2_base.value.value <= field_combo.chip2_base.value.next;
            end
        end
    end
    assign hwif_out.chip2_base.value.value = field_storage.chip2_base.value.value;
    // Field: hyperbus_cfg_regs.chip2_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip2_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip2_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip2_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip2_bound.value.next = next_c;
        field_combo.chip2_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip2_bound.value.value <= 10'h3;
        end else begin
            if(field_combo.chip2_bound.value.load_next) begin
                field_storage.chip2_bound.value.value <= field_combo.chip2_bound.value.next;
            end
        end
    end
    assign hwif_out.chip2_bound.value.value = field_storage.chip2_bound.value.value;
    // Field: hyperbus_cfg_regs.chip3_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip3_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip3_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip3_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip3_base.value.next = next_c;
        field_combo.chip3_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip3_base.value.value <= 10'h3;
        end else begin
            if(field_combo.chip3_base.value.load_next) begin
                field_storage.chip3_base.value.value <= field_combo.chip3_base.value.next;
            end
        end
    end
    assign hwif_out.chip3_base.value.value = field_storage.chip3_base.value.value;
    // Field: hyperbus_cfg_regs.chip3_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip3_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip3_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip3_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip3_bound.value.next = next_c;
        field_combo.chip3_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip3_bound.value.value <= 10'h4;
        end else begin
            if(field_combo.chip3_bound.value.load_next) begin
                field_storage.chip3_bound.value.value <= field_combo.chip3_bound.value.next;
            end
        end
    end
    assign hwif_out.chip3_bound.value.value = field_storage.chip3_bound.value.value;
    // Field: hyperbus_cfg_regs.chip4_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip4_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip4_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip4_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip4_base.value.next = next_c;
        field_combo.chip4_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip4_base.value.value <= 10'h4;
        end else begin
            if(field_combo.chip4_base.value.load_next) begin
                field_storage.chip4_base.value.value <= field_combo.chip4_base.value.next;
            end
        end
    end
    assign hwif_out.chip4_base.value.value = field_storage.chip4_base.value.value;
    // Field: hyperbus_cfg_regs.chip4_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip4_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip4_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip4_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip4_bound.value.next = next_c;
        field_combo.chip4_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip4_bound.value.value <= 10'h5;
        end else begin
            if(field_combo.chip4_bound.value.load_next) begin
                field_storage.chip4_bound.value.value <= field_combo.chip4_bound.value.next;
            end
        end
    end
    assign hwif_out.chip4_bound.value.value = field_storage.chip4_bound.value.value;
    // Field: hyperbus_cfg_regs.chip5_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip5_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip5_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip5_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip5_base.value.next = next_c;
        field_combo.chip5_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip5_base.value.value <= 10'h5;
        end else begin
            if(field_combo.chip5_base.value.load_next) begin
                field_storage.chip5_base.value.value <= field_combo.chip5_base.value.next;
            end
        end
    end
    assign hwif_out.chip5_base.value.value = field_storage.chip5_base.value.value;
    // Field: hyperbus_cfg_regs.chip5_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip5_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip5_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip5_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip5_bound.value.next = next_c;
        field_combo.chip5_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip5_bound.value.value <= 10'h6;
        end else begin
            if(field_combo.chip5_bound.value.load_next) begin
                field_storage.chip5_bound.value.value <= field_combo.chip5_bound.value.next;
            end
        end
    end
    assign hwif_out.chip5_bound.value.value = field_storage.chip5_bound.value.value;
    // Field: hyperbus_cfg_regs.chip6_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip6_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip6_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip6_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip6_base.value.next = next_c;
        field_combo.chip6_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip6_base.value.value <= 10'h6;
        end else begin
            if(field_combo.chip6_base.value.load_next) begin
                field_storage.chip6_base.value.value <= field_combo.chip6_base.value.next;
            end
        end
    end
    assign hwif_out.chip6_base.value.value = field_storage.chip6_base.value.value;
    // Field: hyperbus_cfg_regs.chip6_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip6_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip6_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip6_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip6_bound.value.next = next_c;
        field_combo.chip6_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip6_bound.value.value <= 10'h7;
        end else begin
            if(field_combo.chip6_bound.value.load_next) begin
                field_storage.chip6_bound.value.value <= field_combo.chip6_bound.value.next;
            end
        end
    end
    assign hwif_out.chip6_bound.value.value = field_storage.chip6_bound.value.value;
    // Field: hyperbus_cfg_regs.chip7_base.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip7_base.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip7_base && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip7_base.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip7_base.value.next = next_c;
        field_combo.chip7_base.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip7_base.value.value <= 10'h7;
        end else begin
            if(field_combo.chip7_base.value.load_next) begin
                field_storage.chip7_base.value.value <= field_combo.chip7_base.value.next;
            end
        end
    end
    assign hwif_out.chip7_base.value.value = field_storage.chip7_base.value.value;
    // Field: hyperbus_cfg_regs.chip7_bound.value
    always_comb begin
        automatic logic [9:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.chip7_bound.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.chip7_bound && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.chip7_bound.value.value & ~decoded_wr_biten[31:22]) | (decoded_wr_data[31:22] & decoded_wr_biten[31:22]);
            load_next_c = '1;
        end
        field_combo.chip7_bound.value.next = next_c;
        field_combo.chip7_bound.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.chip7_bound.value.value <= 10'h8;
        end else begin
            if(field_combo.chip7_bound.value.load_next) begin
                field_storage.chip7_bound.value.value <= field_combo.chip7_bound.value.next;
            end
        end
    end
    assign hwif_out.chip7_bound.value.value = field_storage.chip7_bound.value.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [6:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 7'h0) begin
            readback_data_var[3:0] = field_storage.t_latency_access.value.value;
        end
        if(rd_mux_addr == 7'h4) begin
            readback_data_var[0] = field_storage.en_latency_additional.value.value;
        end
        if(rd_mux_addr == 7'h8) begin
            readback_data_var[15:0] = field_storage.t_burst_max.value.value;
        end
        if(rd_mux_addr == 7'hc) begin
            readback_data_var[3:0] = field_storage.t_read_write_recovery.value.value;
        end
        if(rd_mux_addr == 7'h10) begin
            readback_data_var[4:0] = field_storage.t_rx_clk_delay.fine.value;
            readback_data_var[7:5] = field_storage.t_rx_clk_delay.coarse.value;
        end
        if(rd_mux_addr == 7'h14) begin
            readback_data_var[4:0] = field_storage.t_tx_clk_delay.fine.value;
            readback_data_var[7:5] = field_storage.t_tx_clk_delay.coarse.value;
        end
        if(rd_mux_addr == 7'h18) begin
            readback_data_var[4:0] = field_storage.address_mask_msb.value.value;
        end
        if(rd_mux_addr == 7'h1c) begin
            readback_data_var[0] = field_storage.address_space.value.value;
        end
        if(rd_mux_addr == 7'h20) begin
            readback_data_var[0] = field_storage.phys_in_use.value.value;
        end
        if(rd_mux_addr == 7'h24) begin
            readback_data_var[0] = field_storage.which_phy.value.value;
        end
        if(rd_mux_addr == 7'h28) begin
            readback_data_var[3:0] = field_storage.t_csh_cycles.value.value;
        end
        if(rd_mux_addr == 7'h2c) begin
            readback_data_var[3:0] = field_storage.csn_to_ck_cycles.value.value;
        end
        if(rd_mux_addr == 7'h30) begin
            readback_data_var[31:22] = field_storage.chip0_base.value.value;
        end
        if(rd_mux_addr == 7'h34) begin
            readback_data_var[31:22] = field_storage.chip0_bound.value.value;
        end
        if(rd_mux_addr == 7'h38) begin
            readback_data_var[31:22] = field_storage.chip1_base.value.value;
        end
        if(rd_mux_addr == 7'h3c) begin
            readback_data_var[31:22] = field_storage.chip1_bound.value.value;
        end
        if(rd_mux_addr == 7'h40) begin
            readback_data_var[31:22] = field_storage.chip2_base.value.value;
        end
        if(rd_mux_addr == 7'h44) begin
            readback_data_var[31:22] = field_storage.chip2_bound.value.value;
        end
        if(rd_mux_addr == 7'h48) begin
            readback_data_var[31:22] = field_storage.chip3_base.value.value;
        end
        if(rd_mux_addr == 7'h4c) begin
            readback_data_var[31:22] = field_storage.chip3_bound.value.value;
        end
        if(rd_mux_addr == 7'h58) begin
            readback_data_var[31:22] = field_storage.chip4_base.value.value;
        end
        if(rd_mux_addr == 7'h5c) begin
            readback_data_var[31:22] = field_storage.chip4_bound.value.value;
        end
        if(rd_mux_addr == 7'h60) begin
            readback_data_var[31:22] = field_storage.chip5_base.value.value;
        end
        if(rd_mux_addr == 7'h64) begin
            readback_data_var[31:22] = field_storage.chip5_bound.value.value;
        end
        if(rd_mux_addr == 7'h68) begin
            readback_data_var[31:22] = field_storage.chip6_base.value.value;
        end
        if(rd_mux_addr == 7'h6c) begin
            readback_data_var[31:22] = field_storage.chip6_bound.value.value;
        end
        if(rd_mux_addr == 7'h70) begin
            readback_data_var[31:22] = field_storage.chip7_base.value.value;
        end
        if(rd_mux_addr == 7'h74) begin
            readback_data_var[31:22] = field_storage.chip7_bound.value.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
