// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// File auto-generated by Padrick unknown
module hyperbus_padframe_topr_pads
  import pkg_hyperbus_padframe::*;
(
  output pad_domain_topr_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input  pad_domain_topr_static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
 // Dynamic Pad control signals, these signals are controlled by the multiplexer in the correpsongin pad_controller module
  // Landing Pads
  inout wire logic pad_config_tc_pad_internal_signals_0,
  inout wire logic pad_config_tc_pad_internal_signals_1,
  inout wire logic pad_config_tc_pad_internal_signals_2,
  inout wire logic pad_config_tc_pad_internal_signals_3,
  inout wire logic pad_hyper_phy1_cs_n_0_pad,
  inout wire logic pad_hyper_phy1_cs_n_1_pad,
  inout wire logic pad_hyper_phy1_ck_pad,
  inout wire logic pad_hyper_phy1_ck_n_pad,
  inout wire logic pad_hyper_phy1_rwds_pad,
  inout wire logic pad_hyper_phy1_reset_n_pad,
  inout wire logic pad_hyper_phy1_dq_b0_pad,
  inout wire logic pad_hyper_phy1_dq_b1_pad,
  inout wire logic pad_hyper_phy1_dq_b2_pad,
  inout wire logic pad_hyper_phy1_dq_b3_pad,
  inout wire logic pad_hyper_phy1_dq_b4_pad,
  inout wire logic pad_hyper_phy1_dq_b5_pad,
  inout wire logic pad_hyper_phy1_dq_b6_pad,
  inout wire logic pad_hyper_phy1_dq_b7_pad,
  inout wire logic pad_hyper_phy0_cs_n_0_pad,
  inout wire logic pad_hyper_phy0_cs_n_1_pad,
  inout wire logic pad_hyper_phy0_ck_pad,
  inout wire logic pad_hyper_phy0_ck_n_pad,
  inout wire logic pad_hyper_phy0_rwds_pad,
  inout wire logic pad_hyper_phy0_reset_n_pad,
  inout wire logic pad_hyper_phy0_dq_b0_pad,
  inout wire logic pad_hyper_phy0_dq_b1_pad,
  inout wire logic pad_hyper_phy0_dq_b2_pad,
  inout wire logic pad_hyper_phy0_dq_b3_pad,
  inout wire logic pad_hyper_phy0_dq_b4_pad,
  inout wire logic pad_hyper_phy0_dq_b5_pad,
  inout wire logic pad_hyper_phy0_dq_b6_pad,
  inout wire logic pad_hyper_phy0_dq_b7_pad
  );

   // Pad instantiations
   localparam tc_pad_pkg::tc_pad_config_t gf22_invecas_tc_pad_config = '{
      1'b1,   //av_bidir_cell
      1'b0,   //av_in_cell
      1'b0,   //av_out_cell
      1'b1,   //in_en_latch
      1'b1,   //pu_pd_both_en
      1'b0,   //rt_en_ah
      2,      //ds_w
      3       //n_int
  };
  
  wire io_pad_retcin;
  assign io_pad_retcin = 1'b0;
  `define io_pad_internals {pad_config_tc_pad_internal_signals_3, pad_config_tc_pad_internal_signals_2, pad_config_tc_pad_internal_signals_1, pad_config_tc_pad_internal_signals_0}
   tc_pad_pwr_mng #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_mng_north (
    .ret_en_i ( io_pad_retcin     ),
    .int_io   ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_pwr_mng #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_mng_east (
    .ret_en_i ( io_pad_retcin     ),
    .int_io   ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_cs_n_0 (
    .pad_io           ( pad_hyper_phy1_cs_n_0_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_cs_no_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_cs_n_1 (
    .pad_io           ( pad_hyper_phy1_cs_n_1_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_cs_no_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_ck (
    .pad_io           ( pad_hyper_phy1_ck_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_ck_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_ck_n (
    .pad_io           ( pad_hyper_phy1_ck_n_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_ck_no       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_rwds (
    .pad_io           ( pad_hyper_phy1_rwds_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_rwds_i       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_rwds_oe_o       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_rwds_o       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_rwds_oe_o      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_reset_n (
    .pad_io           ( pad_hyper_phy1_reset_n_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_reset_no       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b0 (
    .pad_io           ( pad_hyper_phy1_dq_b0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b0       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b0       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b0      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b1 (
    .pad_io           ( pad_hyper_phy1_dq_b1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b1       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b1       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b2 (
    .pad_io           ( pad_hyper_phy1_dq_b2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b2       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b2       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b2      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b3 (
    .pad_io           ( pad_hyper_phy1_dq_b3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b3       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b3       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b3      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b4 (
    .pad_io           ( pad_hyper_phy1_dq_b4_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b4       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b4       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b4       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b4      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b5 (
    .pad_io           ( pad_hyper_phy1_dq_b5_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b5       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b5       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b5       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b5      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b6 (
    .pad_io           ( pad_hyper_phy1_dq_b6_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b6       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b6       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b6       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b6      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy1_dq_b7 (
    .pad_io           ( pad_hyper_phy1_dq_b7_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy1_dq_i_b7       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b7       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy1_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy1_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy1_dq_o_b7       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy1_dq_oe_o_b7      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy1_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy1_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_cs_n_0 (
    .pad_io           ( pad_hyper_phy0_cs_n_0_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_cs_no_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_cs_n_1 (
    .pad_io           ( pad_hyper_phy0_cs_n_1_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_cs_no_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_ck (
    .pad_io           ( pad_hyper_phy0_ck_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_ck_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_ck_n (
    .pad_io           ( pad_hyper_phy0_ck_n_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_ck_no       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_rwds (
    .pad_io           ( pad_hyper_phy0_rwds_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_rwds_i       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_rwds_oe_o       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_rwds_o       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_rwds_oe_o      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_reset_n (
    .pad_io           ( pad_hyper_phy0_reset_n_pad            ),
    .pad2chip_o       (        ),
    .input_en_i       ( 1'b0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_reset_no       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b0 (
    .pad_io           ( pad_hyper_phy0_dq_b0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b0       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b0       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b0      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b1 (
    .pad_io           ( pad_hyper_phy0_dq_b1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b1       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b1       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b1      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b2 (
    .pad_io           ( pad_hyper_phy0_dq_b2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b2       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b2       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b2      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b3 (
    .pad_io           ( pad_hyper_phy0_dq_b3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b3       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b3       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b3      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b4 (
    .pad_io           ( pad_hyper_phy0_dq_b4_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b4       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b4       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b4       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b4      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b5 (
    .pad_io           ( pad_hyper_phy0_dq_b5_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b5       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b5       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b5       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b5      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b6 (
    .pad_io           ( pad_hyper_phy0_dq_b6_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b6       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b6       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b6       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b6      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_phy0_dq_b7 (
    .pad_io           ( pad_hyper_phy0_dq_b7_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_phy0_dq_i_b7       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b7       ),
    .pu_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pu_en_o          ),
    .pd_en_i          ( static_connection_signals_soc2pad.hyper_phy0_pd_en_o          ),
    .schmitt_en_i     ( static_connection_signals_soc2pad.hyper_phy0_schmitt_en_o     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_phy0_dq_o_b7       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_phy0_dq_oe_o_b7      ),
    .slew_en_i        ( static_connection_signals_soc2pad.hyper_phy0_slew_en_o        ),
    .drive_strength_i ( static_connection_signals_soc2pad.hyper_phy0_drive_strength_o ),
    .int_io           ( `io_pad_internals         )
  );

endmodule : hyperbus_padframe_topr_pads
