// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// File auto-generated by Padrick unknown
package pkg_hyperbus_padframe;

  //Structs for topr

  //Static connections signals
   typedef struct packed {
      logic        hyper_phy0_ck_no;
      logic        hyper_phy0_ck_o;
      logic        hyper_phy0_cs_no_0;
      logic        hyper_phy0_cs_no_1;
      logic        hyper_phy0_dq_o_b0;
      logic        hyper_phy0_dq_o_b1;
      logic        hyper_phy0_dq_o_b2;
      logic        hyper_phy0_dq_o_b3;
      logic        hyper_phy0_dq_o_b4;
      logic        hyper_phy0_dq_o_b5;
      logic        hyper_phy0_dq_o_b6;
      logic        hyper_phy0_dq_o_b7;
      logic        hyper_phy0_dq_oe_o_b0;
      logic        hyper_phy0_dq_oe_o_b1;
      logic        hyper_phy0_dq_oe_o_b2;
      logic        hyper_phy0_dq_oe_o_b3;
      logic        hyper_phy0_dq_oe_o_b4;
      logic        hyper_phy0_dq_oe_o_b5;
      logic        hyper_phy0_dq_oe_o_b6;
      logic        hyper_phy0_dq_oe_o_b7;
      logic       [1:0] hyper_phy0_drive_strength_o;
      logic        hyper_phy0_pd_en_o;
      logic        hyper_phy0_pu_en_o;
      logic        hyper_phy0_reset_no;
      logic        hyper_phy0_rwds_o;
      logic        hyper_phy0_rwds_oe_o;
      logic        hyper_phy0_schmitt_en_o;
      logic        hyper_phy0_slew_en_o;
      logic        hyper_phy1_ck_no;
      logic        hyper_phy1_ck_o;
      logic        hyper_phy1_cs_no_0;
      logic        hyper_phy1_cs_no_1;
      logic        hyper_phy1_dq_o_b0;
      logic        hyper_phy1_dq_o_b1;
      logic        hyper_phy1_dq_o_b2;
      logic        hyper_phy1_dq_o_b3;
      logic        hyper_phy1_dq_o_b4;
      logic        hyper_phy1_dq_o_b5;
      logic        hyper_phy1_dq_o_b6;
      logic        hyper_phy1_dq_o_b7;
      logic        hyper_phy1_dq_oe_o_b0;
      logic        hyper_phy1_dq_oe_o_b1;
      logic        hyper_phy1_dq_oe_o_b2;
      logic        hyper_phy1_dq_oe_o_b3;
      logic        hyper_phy1_dq_oe_o_b4;
      logic        hyper_phy1_dq_oe_o_b5;
      logic        hyper_phy1_dq_oe_o_b6;
      logic        hyper_phy1_dq_oe_o_b7;
      logic       [1:0] hyper_phy1_drive_strength_o;
      logic        hyper_phy1_pd_en_o;
      logic        hyper_phy1_pu_en_o;
      logic        hyper_phy1_reset_no;
      logic        hyper_phy1_rwds_o;
      logic        hyper_phy1_rwds_oe_o;
      logic        hyper_phy1_schmitt_en_o;
      logic        hyper_phy1_slew_en_o;
     } pad_domain_topr_static_connection_signals_soc2pad_t;

   typedef struct packed {
      logic        hyper_phy0_dq_i_b0;
      logic        hyper_phy0_dq_i_b1;
      logic        hyper_phy0_dq_i_b2;
      logic        hyper_phy0_dq_i_b3;
      logic        hyper_phy0_dq_i_b4;
      logic        hyper_phy0_dq_i_b5;
      logic        hyper_phy0_dq_i_b6;
      logic        hyper_phy0_dq_i_b7;
      logic        hyper_phy0_rwds_i;
      logic        hyper_phy1_dq_i_b0;
      logic        hyper_phy1_dq_i_b1;
      logic        hyper_phy1_dq_i_b2;
      logic        hyper_phy1_dq_i_b3;
      logic        hyper_phy1_dq_i_b4;
      logic        hyper_phy1_dq_i_b5;
      logic        hyper_phy1_dq_i_b6;
      logic        hyper_phy1_dq_i_b7;
      logic        hyper_phy1_rwds_i;
     } pad_domain_topr_static_connection_signals_pad2soc_t;


  //Toplevel structs

  typedef struct packed {
    pad_domain_topr_static_connection_signals_pad2soc_t topr;
  } static_connection_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_topr_static_connection_signals_soc2pad_t topr;
  } static_connection_signals_soc2pad_t;



endpackage : pkg_hyperbus_padframe
