// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef HYPERBUS_CFG_REGS_H
#define HYPERBUS_CFG_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - hyperbus_cfg_regs::t_latency_access
#define HYPERBUS_CFG_REGS__T_LATENCY_ACCESS__VALUE_bm 0xf
#define HYPERBUS_CFG_REGS__T_LATENCY_ACCESS__VALUE_bp 0
#define HYPERBUS_CFG_REGS__T_LATENCY_ACCESS__VALUE_bw 4
#define HYPERBUS_CFG_REGS__T_LATENCY_ACCESS__VALUE_reset 0x6

// reg - hyperbus_cfg_regs::en_latency_additional
#define HYPERBUS_CFG_REGS__EN_LATENCY_ADDITIONAL__VALUE_bm 0x1
#define HYPERBUS_CFG_REGS__EN_LATENCY_ADDITIONAL__VALUE_bp 0
#define HYPERBUS_CFG_REGS__EN_LATENCY_ADDITIONAL__VALUE_bw 1
#define HYPERBUS_CFG_REGS__EN_LATENCY_ADDITIONAL__VALUE_reset 0x0

// reg - hyperbus_cfg_regs::t_burst_max
#define HYPERBUS_CFG_REGS__T_BURST_MAX__VALUE_bm 0xffff
#define HYPERBUS_CFG_REGS__T_BURST_MAX__VALUE_bp 0
#define HYPERBUS_CFG_REGS__T_BURST_MAX__VALUE_bw 16
#define HYPERBUS_CFG_REGS__T_BURST_MAX__VALUE_reset 0x15e

// reg - hyperbus_cfg_regs::t_read_write_recovery
#define HYPERBUS_CFG_REGS__T_READ_WRITE_RECOVERY__VALUE_bm 0xf
#define HYPERBUS_CFG_REGS__T_READ_WRITE_RECOVERY__VALUE_bp 0
#define HYPERBUS_CFG_REGS__T_READ_WRITE_RECOVERY__VALUE_bw 4
#define HYPERBUS_CFG_REGS__T_READ_WRITE_RECOVERY__VALUE_reset 0x6

// reg - hyperbus_cfg_regs::t_rx_clk_delay
#define HYPERBUS_CFG_REGS__T_RX_CLK_DELAY__VALUE_bm 0xff
#define HYPERBUS_CFG_REGS__T_RX_CLK_DELAY__VALUE_bp 0
#define HYPERBUS_CFG_REGS__T_RX_CLK_DELAY__VALUE_bw 8
#define HYPERBUS_CFG_REGS__T_RX_CLK_DELAY__VALUE_reset 0x10

// reg - hyperbus_cfg_regs::t_tx_clk_delay
#define HYPERBUS_CFG_REGS__T_TX_CLK_DELAY__VALUE_bm 0xff
#define HYPERBUS_CFG_REGS__T_TX_CLK_DELAY__VALUE_bp 0
#define HYPERBUS_CFG_REGS__T_TX_CLK_DELAY__VALUE_bw 8
#define HYPERBUS_CFG_REGS__T_TX_CLK_DELAY__VALUE_reset 0x10

// reg - hyperbus_cfg_regs::address_mask_msb
#define HYPERBUS_CFG_REGS__ADDRESS_MASK_MSB__VALUE_bm 0x1f
#define HYPERBUS_CFG_REGS__ADDRESS_MASK_MSB__VALUE_bp 0
#define HYPERBUS_CFG_REGS__ADDRESS_MASK_MSB__VALUE_bw 5
#define HYPERBUS_CFG_REGS__ADDRESS_MASK_MSB__VALUE_reset 0x19

// reg - hyperbus_cfg_regs::address_space
#define HYPERBUS_CFG_REGS__ADDRESS_SPACE__VALUE_bm 0x1
#define HYPERBUS_CFG_REGS__ADDRESS_SPACE__VALUE_bp 0
#define HYPERBUS_CFG_REGS__ADDRESS_SPACE__VALUE_bw 1
#define HYPERBUS_CFG_REGS__ADDRESS_SPACE__VALUE_reset 0x0

// reg - hyperbus_cfg_regs::phys_in_use
#define HYPERBUS_CFG_REGS__PHYS_IN_USE__VALUE_bm 0x1
#define HYPERBUS_CFG_REGS__PHYS_IN_USE__VALUE_bp 0
#define HYPERBUS_CFG_REGS__PHYS_IN_USE__VALUE_bw 1
#define HYPERBUS_CFG_REGS__PHYS_IN_USE__VALUE_reset 0x1

// reg - hyperbus_cfg_regs::which_phy
#define HYPERBUS_CFG_REGS__WHICH_PHY__VALUE_bm 0x1
#define HYPERBUS_CFG_REGS__WHICH_PHY__VALUE_bp 0
#define HYPERBUS_CFG_REGS__WHICH_PHY__VALUE_bw 1
#define HYPERBUS_CFG_REGS__WHICH_PHY__VALUE_reset 0x1

// reg - hyperbus_cfg_regs::t_csh_cycles
#define HYPERBUS_CFG_REGS__T_CSH_CYCLES__VALUE_bm 0xf
#define HYPERBUS_CFG_REGS__T_CSH_CYCLES__VALUE_bp 0
#define HYPERBUS_CFG_REGS__T_CSH_CYCLES__VALUE_bw 4
#define HYPERBUS_CFG_REGS__T_CSH_CYCLES__VALUE_reset 0x1

// reg - hyperbus_cfg_regs::csn_to_ck_cycles
#define HYPERBUS_CFG_REGS__CSN_TO_CK_CYCLES__VALUE_bm 0xf
#define HYPERBUS_CFG_REGS__CSN_TO_CK_CYCLES__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CSN_TO_CK_CYCLES__VALUE_bw 4
#define HYPERBUS_CFG_REGS__CSN_TO_CK_CYCLES__VALUE_reset 0x0

// reg - hyperbus_cfg_regs::chip0_base
#define HYPERBUS_CFG_REGS__CHIP0_BASE__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP0_BASE__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP0_BASE__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP0_BASE__VALUE_reset 0x0

// reg - hyperbus_cfg_regs::chip0_bound
#define HYPERBUS_CFG_REGS__CHIP0_BOUND__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP0_BOUND__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP0_BOUND__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP0_BOUND__VALUE_reset 0x10000

// reg - hyperbus_cfg_regs::chip1_base
#define HYPERBUS_CFG_REGS__CHIP1_BASE__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP1_BASE__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP1_BASE__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP1_BASE__VALUE_reset 0x10000

// reg - hyperbus_cfg_regs::chip1_bound
#define HYPERBUS_CFG_REGS__CHIP1_BOUND__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP1_BOUND__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP1_BOUND__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP1_BOUND__VALUE_reset 0x20000

// reg - hyperbus_cfg_regs::chip2_base
#define HYPERBUS_CFG_REGS__CHIP2_BASE__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP2_BASE__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP2_BASE__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP2_BASE__VALUE_reset 0x20000

// reg - hyperbus_cfg_regs::chip2_bound
#define HYPERBUS_CFG_REGS__CHIP2_BOUND__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP2_BOUND__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP2_BOUND__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP2_BOUND__VALUE_reset 0x30000

// reg - hyperbus_cfg_regs::chip3_base
#define HYPERBUS_CFG_REGS__CHIP3_BASE__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP3_BASE__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP3_BASE__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP3_BASE__VALUE_reset 0x30000

// reg - hyperbus_cfg_regs::chip3_bound
#define HYPERBUS_CFG_REGS__CHIP3_BOUND__VALUE_bm 0xffffffff
#define HYPERBUS_CFG_REGS__CHIP3_BOUND__VALUE_bp 0
#define HYPERBUS_CFG_REGS__CHIP3_BOUND__VALUE_bw 32
#define HYPERBUS_CFG_REGS__CHIP3_BOUND__VALUE_reset 0x40000

// addrmap - hyperbus_cfg_regs
typedef struct __attribute__ ((__packed__)) {
    uint32_t t_latency_access;
    uint32_t en_latency_additional;
    uint32_t t_burst_max;
    uint32_t t_read_write_recovery;
    uint32_t t_rx_clk_delay;
    uint32_t t_tx_clk_delay;
    uint32_t address_mask_msb;
    uint32_t address_space;
    uint32_t phys_in_use;
    uint32_t which_phy;
    uint32_t t_csh_cycles;
    uint32_t csn_to_ck_cycles;
    uint32_t chip0_base;
    uint32_t chip0_bound;
    uint32_t chip1_base;
    uint32_t chip1_bound;
    uint32_t chip2_base;
    uint32_t chip2_bound;
    uint32_t chip3_base;
    uint32_t chip3_bound;
} hyperbus_cfg_regs_t;


static_assert(sizeof(hyperbus_cfg_regs_t) == 0x50, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* HYPERBUS_CFG_REGS_H */
